 -- INSERT DE DATOS PARA TIPOS DE IMPUESTOS
INSERT INTO TIPOS_DE_IMPUESTOS VALUES
(1,'IMPUESTO AL VALOR AGREGADO 10%',10),
(2,'IMPUESTO AL VALOR AGREGADO 5%',5),
(3,'EXCENTAS',0)
 --ACTUALIZAR TIPOS DE PRODUCTOS
UPDATE TIPOS_DE_PRODUCTOS SET TIPOS_DE_PRODUCTOS.TIPO_IMPUESTO = 1
WHERE TIPOS_DE_PRODUCTOS.TIPO_PRODUCTO IN (1,4,5,6)
UPDATE TIPOS_DE_PRODUCTOS SET TIPOS_DE_PRODUCTOS.TIPO_IMPUESTO = 2
WHERE TIPOS_DE_PRODUCTOS.TIPO_PRODUCTO IN (2,3)